site_name: Bioinformatics Documentation
theme: null
theme_dir: 'ltu_mb'
pages:
- 'Home': 'index.md'
- 'Tutorials':
  - 'Introduction to HPC': 'tutorials/hpc/index.md'
  - 'Introduction to Unix': 'tutorials/unix/index.md'
extra_templates: [
  'tutorials/hpc/slides.html',
  'tutorials/unix/slides.html',
]
markdown_extensions: [
  'markdown_include.include',
  'showable',
  'markdown.extensions.fenced_code',
  'environment',
]
